[pytest]
markers =
    integration: mark tests as integration tests that may use external resources or longer runtime
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:Data Validation extension is not supported and will be removed:UserWarning:openpyxl
